updates application struture
archesproject/arches-lingo pull request #10
Opened 2024-04-11 05:25 UTC by chrabyrd

2024-06-04 15:50 UTC, robgaston requested changes
@chrabyrd this is looking very close, but we should look at updating the `README.md` and moving from yarn to npm.  thanks!

2024-06-04 15:50 UTC, robgaston commented on README.txt
@chrabyrd we should replace this with content that outlines project setup, as per https://github.com/archesproject/arches_rdm_example_project/blob/main/README.md

2024-06-04 15:50 UTC, robgaston commented on yarn.lock
@chrabyrd as we are moving to npm, shouldn't this be replaced with `package-lock.json`?

2024-06-04 15:52 UTC, chrabyrd commented
> @chrabyrd this is looking very close, but we should look at updating the `README.md` and moving from yarn to npm. thanks!

Ah yes -- this was done before the cutover from yarn to npm. Will update! 👍

2024-06-10 16:09 UTC, robgaston approved these changes

2024-06-10 16:09 UTC, merged