genericizes label viewer
archesproject/arches-lingo pull request #161
Opened 2024-12-23 23:52 UTC by aarongundel

There was a request from @robgaston to genericize the label viewer so it could be used with more than just the appellative status branch.  This is an attempt to do that.  It pulls some of the viewer components back into the SchemeLabel section with the help of named slots.  Seems to work as expected, happy to get feedback on patterns.

2024-12-26 23:03 UTC, aarongundel commented
Per last comment, the viewer is now called "MetaString Viewer" - mostly because we don't have a better name for it, and LabelViewer was no longer accurate.

2024-12-30 21:35 UTC, chrabyrd reviewed
looks good, few small things

2024-12-31 04:40 UTC, aarongundel commented on arches_lingo/src/arches_lingo/components/generic/MetaStringViewer.vue
> +        :pt="{ root: { style: { fontFamily: 'sans-serif' } } }"
perhaps we could create a constant with this object value?  I'm not sure there's a supported way to tweak the base style, though.  cc @jacobtylerwalls

2024-12-31 04:57 UTC, aarongundel commented on arches_lingo/src/arches_lingo/components/generic/MetaStringViewer.vue
> +            severity: "danger",
worth noting - not defined in constants.ts for this project.  Defined in arches references as a constant.  Seems like we shouldn't rely on that.

2024-12-31 04:59 UTC, aarongundel commented on arches_lingo/src/arches_lingo/components/generic/MetaStringViewer.vue
> +        table-style="min-width: 50rem"
yanked, probably copypasta.  No ill effects I've noticed.

2025-01-02 20:10 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/MetaStringViewer.vue
> +            severity: "danger",
oh fair 👍

2025-01-02 20:11 UTC, chrabyrd reviewed
looks good, waiting to  approve til notes section is merged in

2025-01-02 21:27 UTC, chrabyrd requested changes
1 small change, otherwise lgtm 👍

2025-01-02 21:27 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/scheme/report/SchemeLabel.vue
> +                        {{ $gettext("Contributors") }}:
similar here with "naked" strings in HTML

2025-01-02 21:33 UTC, aarongundel commented on arches_lingo/src/arches_lingo/components/scheme/report/SchemeLabel.vue
> +                        {{ $gettext("Contributors") }}:
fixed, included colon in gettext.  🏓

2025-01-02 21:33 UTC, chrabyrd reviewed
🏓

2025-01-02 21:33 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/scheme/report/SchemeLabel.vue
> +                    {{
here too? 🤔

2025-01-02 21:36 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/MetaStringViewer.vue
> +        :pt="{ root: { style: { fontFamily: 'sans-serif' } } }"
I recall the problem is that primevue appends DOM elements for modals and tooltips outside the `<main>` element.

2025-01-02 21:39 UTC, chrabyrd approved these changes
🚀 🚀 🚀

2025-01-02 21:45 UTC, merged