Scheme Label Editor & Reference Datatype Widget
archesproject/arches-lingo pull request #169
Opened 2024-12-31 01:57 UTC by johnatawnclementawn

Resolves #147

2025-01-02 18:25 UTC, chrabyrd reviewed
Looks good! Just some pretty minor stuff -- happy to chat about about any of it

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +// import ResourceInstanceRelationships from "@/arches_lingo/components/generic/ResourceInstanceRelationships.vue";
nit: remove this instead of commenting it out?

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +const appellative_status = ref(props.value);
`camelCase` for JS consts, also why name it differently from `value`?

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +async function getOptions(listId: string): Promise<ControlledListItem[]> {
nit: functions should be declared last, after all consts ( I def need to get that styleguide updated 😅 )

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +        await Promise.all([
this is fine and I'm not blocking on it, but it still may hammer db depending on what the endpoint is doing. Happy to punt though

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/ReferenceDatatype.vue
> +import type {
nit: types are imported last

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/reference-datatype/ReferenceDatatypeEditor.vue
> +        :show-toggle-all="!!options?.length"
shouldn't need `!!`

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/reference-datatype/ReferenceDatatypeEditor.vue
> +const uriRef = ref(
this is pretty complex, and would be more readable/maintainable if broken out into its own function.

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/reference-datatype/ReferenceDatatypeEditor.vue
> +const optionLabels = (item: ControlledListItem): string => {
nit: function declarations should be `function foo() {`

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/reference-datatype/ReferenceDatatypeEditor.vue
> +    const preferredLabel =
this could also be broken out a bit to improve readability

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/reference-datatype/ReferenceDatatypeEditor.vue
> +        :show-toggle-all="!!options?.length"
same here

2025-01-02 18:25 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/constants.ts
> +export const LANGUAGE_CONTROLLED_LIST = "55ce793b-a51a-4b25-811d-d08ea797f8c3";
IMO hardcoding URIs on the frontend isn't a preferred pattern. Is there a way to get these supplied by the backend? If not or if it becomes super complex then okay, but IMO this pattern should be avoided if possible.

2025-01-02 21:01 UTC, johnatawnclementawn commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +// import ResourceInstanceRelationships from "@/arches_lingo/components/generic/ResourceInstanceRelationships.vue";
Two resource instance nodes in this nodegroup, just hadn't stubbed those out - they're now and import is used 👍🏼

2025-01-03 17:51 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +        await Promise.all([
Yeah, let's measure this before we prematurely optimize -- we can always switch to the endpoint that returns all lists and then filter on the frontend.

2025-01-03 19:22 UTC, johnatawnclementawn commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +        await Promise.all([
Switching to that endpoint may be helpful in avoiding hard-coded list id's because there is graph/node info... I just started working with this endpoint because I was wary of passing around the entire CLM

2025-01-03 19:30 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +        await Promise.all([
sweet!

2025-01-08 16:37 UTC, chrabyrd approved these changes
lgtm!

2025-01-08 16:38 UTC, chrabyrd requested changes
whoops, was only looking at a subset of changes. One moment 😅

2025-01-08 17:57 UTC, chrabyrd requested changes
code looks good but there's some functionality issues:

- the dropdowns do not work for a new scheme label

2025-01-08 19:20 UTC, jacobtylerwalls reviewed
Looking great!

2025-01-08 19:20 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/types.ts
> +    guide?: boolean;
Looks like this is morphing into the referencedatatype tile shape instead of the ControlledListItem django model. If that's right, how about we remove these props altogether and rename the type?

2025-01-08 19:20 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/reference-datatype/ReferenceDatatypeEditor.vue
> +        :show-toggle-all="options?.length"
Although I use `.length` in boolean contexts (maybe more than I should), this is a prop doc'd to take a boolean so let's actually pass a boolean, even if it's not happening to break right now.
```suggestion
        :show-toggle-all="options?.length > 0"
```

2025-01-08 19:20 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/reference-datatype/ReferenceDatatypeEditor.vue
> +        :show-toggle-all="options?.length"
<img width="259" alt="Screenshot 2025-01-08 at 2 09 18 PM" src="https://github.com/user-attachments/assets/6eaffb7a-4855-4af9-b254-f080788237f1" />

2025-01-08 19:20 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +    <label for="">{{ $gettext("Label") }}</label>
Let's file a follow-up issue to fix the empty `for` attributes.

2025-01-08 19:20 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +    const parsed = await fetchControlledListOptions(listId);
We don't have a global API client intercepting errors, so we have to manually show errors. Can be a follow-up.

2025-01-08 19:20 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +                formValue.value.tileid as string,
This was already typed well enough
```suggestion
                formValue.value.tileid,
```

2025-01-08 19:37 UTC, chrabyrd commented on arches_lingo/src/arches_lingo/components/generic/reference-datatype/ReferenceDatatypeEditor.vue
> +        :show-toggle-all="options?.length"
would say if we're just casting to a bool then `Boolean()` is more explicit

2025-01-08 19:46 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +                formValue.value.tileid as string,
I fixed this one

2025-01-08 20:15 UTC, robgaston commented
I'm noticing that the tables for Labels and Statements appear to have regressed on this branch, on `main` I see type and language:
![Screenshot 2025-01-08 at 12 14 40 PM](https://github.com/user-attachments/assets/cf9a32d1-68c7-4adb-9860-0d2de4ebf382)
but on this branch they do not appear in the table:
![Screenshot 2025-01-08 at 12 13 22 PM](https://github.com/user-attachments/assets/2407333c-2366-4771-8677-2e909d6af9e6)

2025-01-08 21:42 UTC, johnatawnclementawn commented on arches_lingo/urls.py
> +        name="api-scheme-label-create",
This is the endpoint for POST'ing a single new label tile though. My impression is that you'd only be posting back one new tile at a time

2025-01-08 22:22 UTC, jacobtylerwalls commented on arches_lingo/urls.py
> +        name="api-scheme-label-create",
It's also the endpoint for GETting the whole list, too.

> My impression is that you'd only be posting back one new tile at a time

For sure, but I'm just saying the singular makes it sound like it's a detail view for a single tile, which it isn't.

This is basically just following the example here: https://www.django-rest-framework.org/tutorial/2-requests-and-responses/

e.g.
- route: snippets/
- view: snippet_list
- GET a collection or POST a new one

2025-01-15 18:18 UTC, jacobtylerwalls commented on arches_lingo/serializers.py
> +            ).get(pk=resource_instance_id)
I'm looking into adding a developer convenience for this, either a method `.enrich()` and/or overwriting the `.resourceinstance` descriptor on the TileQuerySet so that it's a lazy getter that calls enrich() for you. 👀

2025-01-15 18:19 UTC, jacobtylerwalls commented on arches_lingo/serializers.py
> +            ).get(pk=resource_instance_id)
(Not suggesting to block this PR on it.)

2025-01-16 00:00 UTC, chrabyrd approved these changes
Overall code looks good, some minor non-blocking nits there.

I'm noticing that I still can't add new labels, and the dropdowns powering the editor still do not show their selection if creating a new label. 

Also I'm noticing this warning in the console now:

```
runtime-core.esm-bundler.js:202 [Vue warn]: Extraneous non-props attributes (pt) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ReferenceDatatypeEditor value=null options= [{…}] multi-value=false  ... > 
  at <ReferenceDatatype value=null mode="edit" multi-value=false  ... > 
  at <LabelEditor value= {tileid: '7b559cf4-77a1-49b3-9116-aabffd464bd3', resourceinstance: 'b73e741b-46da-496c-8960-55cc1007bec4', nodegroup_id: 'ef87ac28-11de-11ef-9493-0a58a9feac02', sortorder: 0, provisionaledits: null, …} onUpdate=fn<update> > 
  at <SchemeLabel mode="edit" tileId="7b559cf4-77a1-49b3-9116-aabffd464bd3" onUpdated=fn<onSectionUpdate>  ... > 
  at <SchemeEditor key=0 editor-max=true editor-form="label"  ... > 
  at <SplitterPanel key=1 size=33 min-size=33  ... > 
  at <Splitter style= {height: '100%'} > 
  at <SchemePage onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <SplitterPanel min-size=25 style= {overflow-y: 'auto'} tabindex="-1" > 
  at <Splitter style= {height: '100%', overflow: 'hidden'} pt= {gutter: {…}} > 
   at <HierarchySplitter key=0 > 
  at <App>
```

but if these are planned to be addressed in followup tickets, I won't block.

2025-01-16 02:05 UTC, johnatawnclementawn commented on arches_lingo/serializers.py
> +            ).get(pk=resource_instance_id)
@jacobtylerwalls I swear this was working yesterday, but when I try to create a new label for an existing scheme self.instance is `None`. Would you be able to take a look at that in my absence?

2025-01-16 02:13 UTC, johnatawnclementawn commented on arches_lingo/src/arches_lingo/components/generic/non-localized-string/NonLocalizedStringEditor.vue
> +    ptId?: string;
Primevue `InputText` doesn't take an ariaLabeledBy prop like some of their other components, so instead I gave that component an Id, hence pass-through Id (ptId). Fixed in latest, but if we start to use these pass-throughs a lot more, I think pt as an object (pattern that primevue uses) is better than this.

2025-01-16 16:21 UTC, jacobtylerwalls commented on arches_lingo/serializers.py
> +            ).get(pk=resource_instance_id)
Done! I think you and I were only testing updates, not creates. I also added a little developer convenience for now.

2025-01-16 16:21 UTC, jacobtylerwalls commented on arches_lingo/serializers.py
> +                label_type = label.appellative_status_ascribed_relation[0]
Added a fix for this, but we probably want a dataclass or something to prevent this awkward double fallback.

2025-01-16 16:21 UTC, jacobtylerwalls commented on arches_lingo/serializers.py
> +                        "A preferred label with the same language already exists for this scheme."
I localized this and borrowed the wording from arches-references to prevent creating a second translatable string.

2025-01-16 16:21 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +const formId = (route.params.id as string) ?? Math.random().toString();
TIL that Vue 3.5 ships a `useId()` hook for this: https://vuejs.org/api/composition-api-helpers.html#useid

That's likely better than rolling our own.

Also: why wouldn't we put this label inside the `<DateDatatypeEditor>` and perhaps use `<label for=` like you had before, instead of passing this down through all these layers?

2025-01-17 23:04 UTC, jacobtylerwalls commented on arches_lingo/src/arches_lingo/components/generic/LabelEditor.vue
> +const formId = (route.params.id as string) ?? Math.random().toString();
Pushed an update to use this

2025-01-17 23:06 UTC, jacobtylerwalls commented on arches_lingo/serializers.py
> +        PREF_LABEL_LIST_ITEM = ListItem.objects.get(list_item_values__value="prefLabel")
Pushed an update for this, a bit silly, but there are probably better things we can do in the future around identifying a list with a natural key (should name be unique, assuming it's not localized?)

2025-01-17 23:11 UTC, jacobtylerwalls commented
> I'm noticing that I still can't add new labels, and the dropdowns powering the editor still do not show their selection if creating a new label.

I fixed this by reverting the revert @johnatawnclementawn added after the demo. Johnathan, let me know if there's a reason you wanted to revert and let's discuss 👍 

> Also I'm noticing this warning in the console now

Fixed in [35a1237](https://github.com/archesproject/arches-lingo/pull/169/commits/35a1237141907ba5161174d9508abf81ddebb82d)

2025-01-17 23:12 UTC, merged