53/54 Migrate lingo collections and graphs to use lists & reference datatype
archesproject/arches-lingo pull request #94
Opened 2024-10-01 18:36 UTC by johnatawnclementawn

2024-10-02 13:46 UTC, johnatawnclementawn commented
@robgaston - happy to rm `lingo_lists.xlsx` in favor of `lingo_lists.json`. The excel file is there because the current iterations of `export_controlled_lists` and `import_controlled_lists` were built to handle that format.

2024-10-04 20:08 UTC, robgaston requested changes
we can just remove the xlsx file here.  otherwise, this looks good to me!

2024-10-04 20:08 UTC, robgaston commented on arches_lingo/pkg/reference_data/controlled_lists/lingo_lists.xlsx
I think we probably can just remove this file since it's not being used during load; seems like it could get confusing with the migration as well if we are loading this in package load

2024-10-17 18:05 UTC, johnatawnclementawn commented
For loading test data use:

# scheme
`python manage.py packages -o import_business_data -s tests/fixtures/data/aat_entries_scheme_examples.json -ow `overwrite
# concept
`python manage.py packages -o import_business_data -s tests/fixtures/data/aat_entries_concept_examples.json -ow overwrite`

2024-10-28 16:39 UTC, merged